### ISSUE TITLE
MagicMirror will not display kalliope?

### ISSUE THREAD

**Issue by maccy99** [kalliope-project/kalliope_neuron_magic_mirror#1]
Hi guys, can someone please help me as i am having trouble displaying kalliope in magic mirror, i have followed it to the letter but it will not display in magic mirror.

in magicmirror.py i cannot for the life of me input the options any other way for : -

mm_url
notifications
payload

can someone please explain how to input the details whether it has to be like : -

        self.mm_url = kwargs.get('http://localhost:8080/kalliope', None)
or
        self.mm_url = kwargs.get(http://localhost:8080/kalliope, None) no '  '
or
        self.mm_url = kwargs.get('http://localhost:8080/kalliope')

and various other ways... been at it now for hours
MMM-kalliope is installed
kalliope_neuron_magic_mirror is installed
kalliope is installed
kalliope_starter_en in installed

i have installed kalliope_neuron_magic_mirror in the cd kalliope_starter_en directory question is, is that correct?

any help would be appreciated as i am very new to this.

regards and thanks in advance

**Comment by Sispheor** [comment]
Hi @maccy99 .
If Kalliope is installed, and if you have a starter kit, you need to create a synapse in your brain.
But, if you want to use the `kalliope_last_tts_message` like in the last synapse example, you need to install kalliope dev version first.
```
cd into kalliope dir
git checkout dev
sudo python setup.py install 
```

If you still have troubles, show us your synapse from your brain. But keep in mind that you never have to update the code.

**Comment by maccy99** [comment]
Hi @Sispheor thank you for your quick response, got it to display now but it works for 3 times then this error occurs and stalls, i have to press Ctrl+C to cancel then restart kalliope start : -

**_Starting REST API Listening port: 5000
Starting Kalliope
Press Ctrl+C for stopping
Starting order signal
Hello Mark
Waiting for trigger detection
yes Mark?
Threshold set to: 4000
Say something!
Google Speech Recognition thinks you said what time is it
Order matched in the brain. Running synapse "say-local-date"
it's 09 and 30 minute
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.1b0-py2.7.egg/kalliope/signals/order/order.py", line 84, in run
    self.start_trigger()
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.4-py2.7.egg/transitions/core.py", line 382, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.4-py2.7.egg/transitions/core.py", line 1020, in _process
    self._transition_queue[0]()
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.4-py2.7.egg/transitions/core.py", line 398, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.4-py2.7.egg/transitions/core.py", line 408, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.4-py2.7.egg/transitions/core.py", line 262, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.4-py2.7.egg/transitions/core.py", line 273, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.4-py2.7.egg/transitions/core.py", line 119, in enter
    event_data.machine.callback(handle, event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.4-py2.7.egg/transitions/core.py", line 990, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.1b0-py2.7.egg/kalliope/signals/order/order.py", line 178, in analysing_order_thread
    is_api_call=False)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.1b0-py2.7.egg/kalliope/core/SynapseLauncher.py", line 99, in run_matching_synapse_from_order
    HookManager.on_processed_synapses()
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.1b0-py2.7.egg/kalliope/core/HookManager.py", line 40, in on_processed_synapses
    return cls.execute_synapses_in_hook_name("on_processed_synapses")
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.1b0-py2.7.egg/kalliope/core/HookManager.py", line 68, in execute_synapses_in_hook_name
    list_synapse = settings.hooks[hook_name]
KeyError: 'on_processed_synapses'_**

brain.yml is: -
```yml

---

  - includes:
        - brains/say.yml
        - brains/systemdate.yml
        - brains/neurotransmitter.yml
        - brains/uri.yml

  - name: "mm-send-message"
    signals:
      - order: "send a message to my magic mirror"
    neurons:
      - magic_mirror:
          mm_url: "http://127.0.0.1:8080/kalliope"
          notification: "KALLIOPE"
          payload: "this message will be printed on the screen"

  - name: "mm-alert"
    signals:
      - order: "send an alert to magic mirror"
    neurons:
      - magic_mirror:
          mm_url: "http://127.0.0.1:8080/kalliope"
          notification: "SHOW_ALERT"
          payload:
            title: "my alert title"
            message: "the message"
            timer: 5000

  - name: "mm-say"
    signals: []
    neurons:
      - magic_mirror:
          mm_url: "http://127.0.0.1:8080/kalliope"
          notification: "KALLIOPE"
          payload: "{{ kalliope_memory['kalliope_last_tts_message'] }}"

  - name: "order-not-found-synapse"
    signals: []
    neurons:
      - say:
          message:
            - "I haven't understood"
            - "I don't know this order"
            - "Please renew your order"
            - "Would you please reword your order"
            - "Can ou please reformulate your order"
            - "I don't recognize that order"

  - name: "on-triggered-synapse"
    signals: []
    neurons: 
      - say:
          message:
            - "yes Mark?"
            - "I'm listening"
            - "I'm listening to you"
            - "Hi Mark?"
            - "Hi Mark, what can i do for you?"
            - "Speaking"
            - "how can i help you Mark?"

  - name: "on-start-synapse"
    signals: []
    neurons:
      - say:
          message: "Hello Mark"
```

regards

**Comment by maccy99** [comment]
sorry forgot to mention I'm using 

> kalliope starter en

**Comment by Sispheor** [comment]
Yes, as you've downloaded the last dev. you need to add this hook in your settings: `on_processed_synapses`. The key must to be declared, even if empty.

E.g:
```yml
hooks:
  on_start: "on-start-synapse"
  on_waiting_for_trigger:
  on_triggered: "on-triggered-synapse"
  on_start_listening:
  on_stop_listening:
  on_order_found:
  on_order_not_found: "order-not-found-synapse"
  on_processed_synapses:
  on_mute:
  on_unmute:
  on_start_speaking:
  on_stop_speaking:
```
